# Generated by Django 5.2.4 on 2025-07-03 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_farmacia', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('clase', models.CharField(max_length=100)),
                ('precio_unitario', models.FloatField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='farmacia_app.farmacia')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('farmacia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='farmacia_app.farmacia')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('precio_unitarioC', models.FloatField()),
                ('total_compra', models.FloatField()),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='farmacia_app.farmacia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('sales', models.FloatField()),
                ('igv', models.FloatField()),
                ('total', models.FloatField()),
                ('moneda', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=20)),
                ('tipo_comp', models.CharField(max_length=10)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia_app.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='farmacia_app.farmacia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia_app.producto')),
            ],
            options={
                'verbose_name_plural': 'Inventario Farmacias',
                'unique_together': {('farmacia', 'producto')},
            },
        ),
    ]
